### ISSUE TITLE
Audio Buffer causes OOM on Container in K8s Pod

### ISSUE THREAD

**Issue by justinthelaw** [defenseunicorns/doug-translate#43]
Even for relatively short/small audio files, e.g. >20MB / > 10min, causes the pod to crash due to RAM constraints. For scalability, the way audio is sent to the OpenAI API should be streamed or as a single file without loading all the data to memory.

**Comment by Noxsios** [comment]
This may be due to the current k8s resource limits configured, in a pending PR https://github.com/defenseunicorns/doug-translate/pull/44/commits/e20c158b97bee704a9e5b94cad6364075c3ef576 I increased the limits to better match the NodeJS limits in the Dockerfile

**Comment by justinthelaw** [comment]
@Noxsios yeah, I was able to test in-cluster yesterday. I made a comment on your PR and I'll cut one for this specific issue/concern so that it doesn't dilute your download button PR.
