### ISSUE TITLE
Download Transcript returning [object Object]

### ISSUE THREAD

**Issue by gphorvath** [defenseunicorns/doug-translate#68]
Transcript: [kingofthesnakes_01_baskerville_64kb.mp3-transcript.txt](https://github.com/defenseunicorns/doug-translate/files/13350824/kingofthesnakes_01_baskerville_64kb.mp3-transcript.txt)

**Comment by justinthelaw** [comment]
The download buttons for transcripts and summaries are working. We were able to confirm that the current version of doug-translate on the main branch is functioning properly on an M1 MacBook, WSL Ubuntu 22.04.3, and two Ubuntu 22.04.3 LTS machines.

We recommend re-cloning or pulling from main, installing, and running from a private/incognito window (Edge, Chrome, Firefox, or Brave) in case of browser caching.
