### ISSUE TITLE
Summarize timer seems off

### ISSUE THREAD

**Issue by gphorvath** [defenseunicorns/doug-translate#69]
Two problems... First, summary time still shows transcription. Also, the duration seems to be off. I'm eyeballing it, but it seems to be calculating summary time from the beginning of transcription - which is a problem is the user walks away from the machine in the middle of transcription and comes back later to hit summary.

![image](https://github.com/defenseunicorns/doug-translate/assets/17520730/cec27daf-7186-45d3-acb2-5d38b9173b43)

**Comment by gphorvath** [comment]
Just for kicks I ran a quick test and here are the results
> Clock Time |  Action Taken
1047 | begin transcribe
1048 | transcribe finished (UI displays completed in ~40 seconds)
1052 | start summarize
1053 | summarize finished - (UI displays completed in ~348 seconds)

**Comment by CollectiveUnicorn** [comment]
This is resolved now with a separate summarization and transcription timer.
